name: build

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: [self-hosted, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'AlenDemiro017'

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Run NPM Install
        run: npm Install

      - name: Build the project
        run: npm run build
        
