name: main

on:
  push:
    branches:
      - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        
    - name: Run NPM Install
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Copy files to remote server
      run: |
       echo "${{ secrets.KEY }}" > key.pem
       chmod 400 key.pem
       scp -r -i key.pem -o StrictHostKeyChecking=no dist/** root@46.101.98.114:/var/www/site
