name: main

on:
  push:
    branches:
      - master


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Run NPM Install
      run: npm install
    - name: Build the project 2
      run: npm run build
    - name: Zip artifact
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r artifact.zip ./dist/MyDreamApp
    - name: scp to GCP
      run: |
       echo "${{ secrets.KEY }}" > key.pem
       chmod 400 key.pem
       scp -i key.pem -o StrictHostKeyChecking=no artifact.zip ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/.
    - name: unzip & remove artifact
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no -T root@${{ secrets.HOST }} << EOF
        unzip artifact.zip &&
        rm artifact.zip &&
        rm -rf MyDreamApp &&
        cd dist &&
        mv MyDreamApp ../ &&
        cd .. && rm -rf dist
